#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("L_Sample.Resource", IsApplication=true)]

namespace L_Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040007
			public const int color_1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int color_2 = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int xam_blue = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int xam_dark_blue = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int xam_gray = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int xam_green = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int xam_light_gray = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int xam_medium_blue = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int xam_purple = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int checkBox1 = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int editText1 = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int myButton = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int radioButton1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int radioButton2 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int radioButton3 = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int radioGroup1 = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int seekBar1 = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int textView = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int desc_text = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
